/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Sarahi
 */
public class VP extends javax.swing.JFrame {

    /**
     * Creates new form VP
     */
    public VP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 761, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );

        jMenuBar2.setBackground(new java.awt.Color(0, 0, 51));
        jMenuBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar2.setForeground(new java.awt.Color(51, 255, 255));

        jMenu3.setBackground(new java.awt.Color(51, 255, 255));
        jMenu3.setForeground(new java.awt.Color(51, 255, 255));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Item.png"))); // NOI18N
        jMenu3.setText("Item");
        jMenu3.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N

        jMenuItem1.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/crearItem.png"))); // NOI18N
        jMenuItem1.setText("Crear");
        jMenu3.add(jMenuItem1);

        jMenuItem3.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem3.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/modificarItem.png"))); // NOI18N
        jMenuItem3.setText("Modificar");
        jMenu3.add(jMenuItem3);

        jMenuItem2.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/consultarItem.png"))); // NOI18N
        jMenuItem2.setText("Consultar");
        jMenu3.add(jMenuItem2);

        jMenuItem4.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem4.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/borrarItem.png"))); // NOI18N
        jMenuItem4.setText("Borrar");
        jMenu3.add(jMenuItem4);

        jMenuBar2.add(jMenu3);

        jMenu2.setBackground(new java.awt.Color(51, 255, 255));
        jMenu2.setForeground(new java.awt.Color(51, 255, 255));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Persona.png"))); // NOI18N
        jMenu2.setText("Persona");
        jMenu2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N

        jMenuItem5.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem5.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/crearPersona.png"))); // NOI18N
        jMenuItem5.setText("Crear");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem6.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/modificarPersona.png"))); // NOI18N
        jMenuItem6.setText("Modificar");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem7.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/consultarPersona.png"))); // NOI18N
        jMenuItem7.setText("Consultar");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem8.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/borrarPersona.png"))); // NOI18N
        jMenuItem8.setText("Borrar");
        jMenu2.add(jMenuItem8);

        jMenuBar2.add(jMenu2);

        jMenu4.setBackground(new java.awt.Color(51, 255, 255));
        jMenu4.setForeground(new java.awt.Color(51, 255, 255));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Categoría.png"))); // NOI18N
        jMenu4.setText("Categoría");
        jMenu4.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N

        jMenuItem9.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem9.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem9.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/crearCategoría.png"))); // NOI18N
        jMenuItem9.setText("Crear");
        jMenu4.add(jMenuItem9);

        jMenuItem10.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem10.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem10.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/modificarCategoría.png"))); // NOI18N
        jMenuItem10.setText("Modificar");
        jMenu4.add(jMenuItem10);

        jMenuItem11.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem11.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem11.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/consultaCategoría.png"))); // NOI18N
        jMenuItem11.setText("Consultar");
        jMenu4.add(jMenuItem11);

        jMenuItem12.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem12.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem12.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/borrarCategoría.png"))); // NOI18N
        jMenuItem12.setText("Borrar");
        jMenu4.add(jMenuItem12);

        jMenuBar2.add(jMenu4);

        jMenu1.setBackground(new java.awt.Color(51, 255, 255));
        jMenu1.setForeground(new java.awt.Color(51, 255, 255));
        jMenu1.setText("Tipo");
        jMenu1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N

        jMenuItem13.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem13.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem13.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem13.setText("Crear");
        jMenu1.add(jMenuItem13);

        jMenuItem14.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem14.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem14.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem14.setText("Modificar");
        jMenu1.add(jMenuItem14);

        jMenuItem15.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem15.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem15.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem15.setText("Consultar");
        jMenu1.add(jMenuItem15);

        jMenuItem16.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem16.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem16.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem16.setText("Borrar");
        jMenu1.add(jMenuItem16);

        jMenuBar2.add(jMenu1);

        jMenu5.setBackground(new java.awt.Color(51, 255, 255));
        jMenu5.setForeground(new java.awt.Color(51, 255, 255));
        jMenu5.setText("Préstamo");
        jMenu5.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N

        jMenuItem17.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem17.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem17.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem17.setText("Hacer Préstamo");
        jMenu5.add(jMenuItem17);

        jMenuItem18.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem18.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem18.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem18.setText("Agregar Item");
        jMenu5.add(jMenuItem18);

        jMenuItem19.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem19.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem19.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem19.setText("Eiminar Item");
        jMenu5.add(jMenuItem19);

        jMenuItem20.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem20.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem20.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem20.setText("Retornar Item");
        jMenu5.add(jMenuItem20);

        jMenuItem21.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem21.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem21.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem21.setText("Finalizar Préstamo");
        jMenu5.add(jMenuItem21);

        jMenuBar2.add(jMenu5);

        jMenu6.setBackground(new java.awt.Color(51, 255, 255));
        jMenu6.setForeground(new java.awt.Color(51, 255, 255));
        jMenu6.setText("Reporte");
        jMenu6.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N

        jMenuItem22.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem22.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem22.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem22.setText("Por Usuario");
        jMenu6.add(jMenuItem22);

        jMenuItem23.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem23.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem23.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem23.setText("Por Item");
        jMenu6.add(jMenuItem23);

        jMenuItem24.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem24.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem24.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem24.setText("Por Categoria");
        jMenu6.add(jMenuItem24);

        jMenuItem25.setBackground(new java.awt.Color(0, 51, 51));
        jMenuItem25.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jMenuItem25.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem25.setText("Por Tipo");
        jMenu6.add(jMenuItem25);

        jMenuBar2.add(jMenu6);

        jMenu7.setBackground(new java.awt.Color(51, 255, 255));
        jMenu7.setForeground(new java.awt.Color(51, 255, 255));
        jMenu7.setText("Acerca");
        jMenu7.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jMenuBar2.add(jMenu7);

        jMenu8.setBackground(new java.awt.Color(51, 255, 255));
        jMenu8.setForeground(new java.awt.Color(51, 255, 255));
        jMenu8.setText("Salir");
        jMenu8.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jMenuBar2.add(jMenu8);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
