/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Sarahi
 */
public class VP extends javax.swing.JFrame {

    /**
     * Creates new form VP
     */
    public VP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        crearItem = new javax.swing.JMenuItem();
        modificarItem = new javax.swing.JMenuItem();
        borrarItem = new javax.swing.JMenuItem();
        consultarItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        crearUsuario = new javax.swing.JMenuItem();
        modificarUsuario = new javax.swing.JMenuItem();
        borrarUsuario = new javax.swing.JMenuItem();
        consultarUsuario = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        crearCategoria = new javax.swing.JMenuItem();
        modificarCategoria = new javax.swing.JMenuItem();
        borrarCategoria = new javax.swing.JMenuItem();
        consutarCategoria = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        crearTipo = new javax.swing.JMenuItem();
        modificarTipo = new javax.swing.JMenuItem();
        borrarTipo = new javax.swing.JMenuItem();
        consultarTipo = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setBorder(null);
        jMenu1.setText("Item");

        crearItem.setText("Crear");
        crearItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearItemActionPerformed(evt);
            }
        });
        jMenu1.add(crearItem);
        crearItem.getAccessibleContext().setAccessibleName("");

        modificarItem.setText("Modificar");
        modificarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarItemActionPerformed(evt);
            }
        });
        jMenu1.add(modificarItem);

        borrarItem.setText("Borrar");
        jMenu1.add(borrarItem);

        consultarItem.setText("Consultar");
        jMenu1.add(consultarItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(null);
        jMenu2.setText("Usuario");

        crearUsuario.setText("Crear");
        crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(crearUsuario);

        modificarUsuario.setText("Modificar");
        modificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(modificarUsuario);

        borrarUsuario.setText("Borrar");
        jMenu2.add(borrarUsuario);

        consultarUsuario.setText("Consultar");
        jMenu2.add(consultarUsuario);

        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(null);
        jMenu3.setText("Categoría");

        crearCategoria.setText("Crear");
        crearCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCategoriaActionPerformed(evt);
            }
        });
        jMenu3.add(crearCategoria);

        modificarCategoria.setText("Modificar");
        modificarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarCategoriaActionPerformed(evt);
            }
        });
        jMenu3.add(modificarCategoria);

        borrarCategoria.setText("Borrar");
        jMenu3.add(borrarCategoria);

        consutarCategoria.setText("Consultar");
        jMenu3.add(consutarCategoria);

        jMenuBar1.add(jMenu3);

        jMenu4.setBorder(null);
        jMenu4.setText("Tipo");

        crearTipo.setText("Crear");
        crearTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearTipoActionPerformed(evt);
            }
        });
        jMenu4.add(crearTipo);
        crearTipo.getAccessibleContext().setAccessibleName("Crear");

        modificarTipo.setText("Modificar");
        modificarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarTipoActionPerformed(evt);
            }
        });
        jMenu4.add(modificarTipo);

        borrarTipo.setText("Borrar");
        jMenu4.add(borrarTipo);

        consultarTipo.setText("Consultar");
        jMenu4.add(consultarTipo);

        jMenuBar1.add(jMenu4);
        jMenu4.getAccessibleContext().setAccessibleName("crearTipo");

        jMenu5.setBorder(null);
        jMenu5.setText("Préstamo");
        jMenuBar1.add(jMenu5);

        jMenu6.setBorder(null);
        jMenu6.setText("Reporte");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 761, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearItemActionPerformed
        // TODO add your handling code here:
        new CrearItem(this, true).setVisible(true);
    }//GEN-LAST:event_crearItemActionPerformed

    private void crearTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearTipoActionPerformed
        // TODO add your handling code here:
        new CrearTipo (this, true).setVisible(true);
    }//GEN-LAST:event_crearTipoActionPerformed

    private void modificarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarItemActionPerformed
        // TODO add your handling code here:
        new ModificarItem(this, true).setVisible(true);
    }//GEN-LAST:event_modificarItemActionPerformed

    private void crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearUsuarioActionPerformed

    private void modificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarUsuarioActionPerformed

    private void crearCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearCategoriaActionPerformed

    private void modificarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarCategoriaActionPerformed

    private void modificarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem borrarCategoria;
    private javax.swing.JMenuItem borrarItem;
    private javax.swing.JMenuItem borrarTipo;
    private javax.swing.JMenuItem borrarUsuario;
    private javax.swing.JMenuItem consultarItem;
    private javax.swing.JMenuItem consultarTipo;
    private javax.swing.JMenuItem consultarUsuario;
    private javax.swing.JMenuItem consutarCategoria;
    private javax.swing.JMenuItem crearCategoria;
    private javax.swing.JMenuItem crearItem;
    private javax.swing.JMenuItem crearTipo;
    private javax.swing.JMenuItem crearUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem modificarCategoria;
    private javax.swing.JMenuItem modificarItem;
    private javax.swing.JMenuItem modificarTipo;
    private javax.swing.JMenuItem modificarUsuario;
    // End of variables declaration//GEN-END:variables
}
